### ISSUE TITLE
Team page UI:  member card

### ISSUE THREAD

**Issue by AlacritousCreature** [Elevate-Lab/GDSC-IIIT-A-Community-Website#11]
After issue #10 gets done....insert member card in each section and check by inserting multiple if does not hurt the alignment.

member card should have space for image, name, some social media icons that can be linked of each ones handles, and edit, delete button at bottom.

**Comment by AlacritousCreature** [comment]
@the-grignard-reagent  updates?

**Comment by AlacritousCreature** [comment]
@shin-igami updates?

**Comment by shin-igami** [comment]
> @shin-igami updates?

Sorry mam I didn't see this issue. I will now start working on it.
