### ISSUE TITLE
Projects Page UI

### ISSUE THREAD

**Issue by AlacritousCreature** [Elevate-Lab/GDSC-IIIT-A-Community-Website#27]
Insert a introductory section on projects page like below-
![a](https://user-images.githubusercontent.com/58398802/138934579-585b8bea-b922-478c-9aa6-202b3d05114b.png)
![b](https://user-images.githubusercontent.com/58398802/138934598-770444f7-14d3-4077-a9bf-b741e7311d38.png)

This can be referred from below website-
https://www.dscvjti.tech/

**Comment by shlesh** [comment]
@AlacritousCreature maam can I work on this please?

**Comment by AlacritousCreature** [comment]
Sure

**Comment by AlacritousCreature** [comment]
@shlesh  updates?

**Comment by shlesh** [comment]
> 
> 
> @shlesh updates?

Will update/try to finish by tonight maam!!

**Comment by AlacritousCreature** [comment]
@shlesh  is it done?

**Comment by AlacritousCreature** [comment]
cancelled.
