### ISSUE TITLE
Team page UI

### ISSUE THREAD

**Issue by AlacritousCreature** [Elevate-Lab/GDSC-IIIT-A-Community-Website#28]
Insert a moving carousel (image gallery kind) in start of team page
![pio](https://user-images.githubusercontent.com/58398802/138935323-05a71653-61a0-4e80-b689-f64190b06a5e.png)
.
this can be referred on below site-
https://dscsrm.com/

**Comment by AlacritousCreature** [comment]
updates?

**Comment by sauhard22** [comment]
> updates?

sorry for the delay, changes pushed to the branch team-page-ui

**Comment by AlacritousCreature** [comment]
@sauhard22  the team-page-ui has no new changes in it...
