### ISSUE TITLE
Add '+' button on events, project, team and blogs page, fix the icons on footer, insert the headline on projects page and align headline on projects and events page

### ISSUE THREAD

**Issue by AlacritousCreature** [Elevate-Lab/GDSC-IIIT-A-Community-Website#35]
1) Add a '+' button on above mentioned pages, at top right corner inside the card's container. For teams page add '+' under the respective sections....like below

![2](https://user-images.githubusercontent.com/58398802/141441547-244137d0-4596-4edd-868b-e7d82c1686ab.png)

![4](https://user-images.githubusercontent.com/58398802/141441621-49cbca3f-531e-4243-aa6e-fbdcb520a981.png)

Find one like below

![1](https://user-images.githubusercontent.com/58398802/141441639-b376406c-b7d5-43b7-9c9c-759de5ae65e8.png)

2) The icons on footer aren't on the correct place, fix that. also navbar doesn't stick to top upon scrolling. make it stick to the top.

3) Insert headline as blogs page on events and project page, also see to their responsiveness, it should go like below
![5](https://user-images.githubusercontent.com/58398802/141441885-ffa6bb93-9fda-4af7-bd63-005552b63d54.png)

events page headline isn't in the center....

![7](https://user-images.githubusercontent.com/58398802/141441950-37acc880-e959-40e4-9522-dfbcad654443.png)

4) make the headline on events page of red color, projects as blue, blogs as green, and teams as yellow, use the google logo standard color.

DEADLINE : 15TH NOV

**Comment by Priyal-Saxena** [comment]
okk mam

**Comment by AlacritousCreature** [comment]
@Priyal-Saxena  updates?

**Comment by Priyal-Saxena** [comment]
> @Priyal-Saxena updates?

will finish by tonight mam.

**Comment by AlacritousCreature** [comment]
Okay
