### ISSUE TITLE
2 small sections + one must read blog section + place '+' buttons at correct position as in design

### ISSUE THREAD

**Issue by AlacritousCreature** [Elevate-Lab/GDSC-IIIT-A-Community-Website#70]
![000](https://user-images.githubusercontent.com/58398802/145358113-02349cfa-98bb-4e1a-b786-e70835da5a05.png)
![676](https://user-images.githubusercontent.com/58398802/145358135-6895d9f8-09c5-4205-8a0d-aab1e85b11e7.png)
![90](https://user-images.githubusercontent.com/58398802/145358160-8f04840c-1c94-4011-a20a-14ba0e4cff09.png)

**Comment by AlacritousCreature** [comment]
@Priyal-Saxena complete it by tomorrow...

**Comment by Priyal-Saxena** [comment]
> @Priyal-Saxena complete it by tomorrow...

okk mam
