### ISSUE TITLE
Events Page UI: Insert Events Cards

### ISSUE THREAD

**Issue by AlacritousCreature** [Elevate-Lab/GDSC-IIIT-A-Community-Website#8]
Below introductory cards insert suitable and creative events card. cards should have space for image, event name, short description and edit, delete button at bottom. 
Note: check by inserting multiple if its one that form grid. if it goes one below other(one in single row), then check by inserting multiple, to check if it does not mess the alignment.

**Comment by AlacritousCreature** [comment]
updates?

**Comment by shlesh** [comment]
> 
> 
> updates?

Will try to finish it off by today maam!
really sorry for the delay

**Comment by AlacritousCreature** [comment]
okay!

**Comment by AlacritousCreature** [comment]
Hey @shlesh ! the cards are good, but somewhere not matching our ui, also we want the site to look different and not to repeat
any design twice. Previously inserted blogs cards were 3 in a row, and since you have inserted 3 in row, i suggest just change it to 2 in a row and make place for the event cards attributes in it..

**Comment by shlesh** [comment]
> Hey @shlesh ! the cards are good, but somewhere not matching our ui, also we want the site to look different and not to repeat
> any design twice. Previously inserted blogs cards were 3 in a row, and since you have inserted 3 in row, i suggest just change it to 2 in a row and make place for the event cards attributes in it..
> Also change the KNOW MORE and C2A buttons style a little..

Thank you soo much for the input maam!!! 
Will do the changes as suggested and make PR by tonight🤘
