### ISSUE TITLE
Projects Page UI: Insert suitable project card

### ISSUE THREAD

**Issue by AlacritousCreature** [Elevate-Lab/GDSC-IIIT-A-Community-Website#9]
Insert suitable and creative projects card. 
card should have space for image, title, and a little description and also edit and delete button at bottom.
Note: check by inserting multiple if its one that form grid. if it goes one below other(one in single row), then check by inserting multiple, to check if it does not mess the alignment.

**Comment by Priyal-Saxena** [comment]
mam, I have the cards, they look like following -
![image](https://user-images.githubusercontent.com/76258252/139507692-ee992a33-2fc8-4dbd-9a99-725df3593590.png)

but the problem is due to previous merge conflicts, I'm not able to open a new PR. How do I solve them?

**Comment by AlacritousCreature** [comment]
updates?

**Comment by Priyal-Saxena** [comment]
mam, I have completed the required changes and created a new PR, please review it.

**Comment by AlacritousCreature** [comment]
Hey @Priyal-Saxena ! the project cards are satisfying our need for displaying the projects, but don't you think they are too minimal for the ui of this website...last time too I had told you that the cards you showed don't match the UI, and are too simple for it. Search on net and you will find a hell lot of good cards.

Though it is merged you need to change it....
As blogs cards goes 3 in a row and event cards would go 2 in a row, and we don't want to repeat any design in our website, you need to find cards that will go one in a row. see the below pics for reference....

makes the required changes and please don't let to say anything after this one is done...

![1](https://user-images.githubusercontent.com/58398802/141089794-3c9fc13e-92c1-4f79-b019-b0b3b26c0eb8.png)
![2](https://user-images.githubusercontent.com/58398802/141089810-4cbc4fdb-0788-4c55-bb3b-0ec0ea25752a.png)

![3](https://user-images.githubusercontent.com/58398802/141089826-f0f8b843-dc05-4c1b-8dec-8a69e7ea732b.png)
![4](https://user-images.githubusercontent.com/58398802/141089851-18cd1dd4-5538-4e72-9bfe-587a68e9e416.png)
